/* eslint-disable no-console */
/**
 * Generates a single, self-contained HTML report from the latest run that you
 * can open in any browser and attach to an email - no SMTP, no credentials.
 *
 *   npm test               # writes test-results/results.json
 *   npm run report:file    # writes reports/PBM-Report-<timestamp>.html
 */
const fs = require('fs');
const path = require('path');
const { readSummary, STATUS_LABEL } = require('./lib/reportSummary');

const OUT_DIR = path.resolve(__dirname, '..', 'reports');
const RESULTS_JSON = path.join(OUT_DIR, 'results.json');

const STATUS_COLOR = {
  expected: '#27ae60',
  unexpected: '#c0392b',
  flaky: '#e67e22',
  skipped: '#7f8c8d',
};

function escapeHtml(s) {
  return String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

function stamp(d) {
  const p = (n) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}_${p(d.getHours())}-${p(d.getMinutes())}-${p(d.getSeconds())}`;
}

function shortFile(file) {
  return file ? file.split(/[\\/]/).pop() : 'other';
}

function buildHtml(summary) {
  const { counts, specs, durationSec, runAt } = summary;
  const headline = counts.failed > 0 ? '#c0392b' : '#27ae60';

  // Group specs by spec file for readability.
  const byFile = {};
  for (const s of specs) {
    const key = shortFile(s.file);
    (byFile[key] = byFile[key] || []).push(s);
  }

  const groups = Object.keys(byFile)
    .sort()
    .map((file) => {
      const rows = byFile[file]
        .map((s) => {
          const label = STATUS_LABEL[s.status] || s.status;
          const color = STATUS_COLOR[s.status] || '#555';
          return (
            `<tr><td class="st"><span class="badge" style="background:${color}">${label}</span></td>` +
            `<td>${escapeHtml(s.title)}</td></tr>`
          );
        })
        .join('');
      return `<h3>${escapeHtml(file)}</h3><table>${rows}</table>`;
    })
    .join('');

  const tile = (label, value, color) =>
    `<div class="tile"><div class="num" style="color:${color}">${value}</div><div class="lbl">${label}</div></div>`;

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>PBM Automation Report - ${runAt}</title>
<style>
  body{font-family:Arial,Helvetica,sans-serif;margin:0;background:#f4f6f8;color:#222}
  .wrap{max-width:900px;margin:0 auto;padding:24px}
  h1{margin:0 0 4px;font-size:22px}
  .meta{color:#667;font-size:13px;margin-bottom:18px}
  .tiles{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:22px}
  .tile{flex:1;min-width:120px;background:#fff;border:1px solid #e3e8ee;border-radius:8px;padding:14px 16px;text-align:center}
  .num{font-size:28px;font-weight:700}
  .lbl{font-size:12px;color:#667;text-transform:uppercase;letter-spacing:.04em;margin-top:2px}
  h3{margin:20px 0 6px;font-size:14px;color:#334}
  table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e3e8ee;border-radius:8px;overflow:hidden}
  td{padding:7px 12px;border-bottom:1px solid #eef2f6;font-size:13px;vertical-align:top}
  tr:last-child td{border-bottom:none}
  td.st{width:90px;white-space:nowrap}
  .badge{color:#fff;font-size:11px;font-weight:700;padding:2px 8px;border-radius:10px}
  .foot{color:#99a;font-size:12px;margin-top:20px}
</style></head>
<body><div class="wrap">
  <h1>PBM Automation — Create New Payer Organization Record</h1>
  <div class="meta">Run at ${escapeHtml(runAt)} &middot; Duration ${durationSec}s</div>
  <div class="tiles">
    ${tile('Total', counts.total, '#222')}
    ${tile('Passed', counts.passed, '#27ae60')}
    ${tile('Failed', counts.failed, headline)}
    ${tile('Flaky', counts.flaky, '#e67e22')}
    ${tile('Skipped', counts.skipped, '#7f8c8d')}
  </div>
  ${groups}
  <div class="foot">Generated by npm run report:file</div>
</div></body></html>`;
}

function main() {
  const summary = readSummary(RESULTS_JSON);
  if (!summary) {
    console.error(`\n[report:file] No results at ${RESULTS_JSON}. Run the tests first (e.g. "npm test").\n`);
    process.exit(1);
  }
  if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR, { recursive: true });

  const file = path.join(OUT_DIR, `PBM-Report-${stamp(new Date())}.html`);
  fs.writeFileSync(file, buildHtml(summary), 'utf-8');

  const { counts } = summary;
  console.log(
    `[report:file] Report written:\n  ${file}\n` +
      `  Passed ${counts.passed}/${counts.total} | Failed ${counts.failed} | Flaky ${counts.flaky} | Skipped ${counts.skipped}\n` +
      `  Open it in a browser and attach it to your email.`,
  );
}

main();
